// Local host
### Home page
GET http://localhost:3000

### All books
GET http://localhost:3000/books

### Single book
GET http://localhost:3000/books/[ID]

### Create book
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
    "title": "Sample Book",
    "author": "John Author",
    "genre": "Fiction",
    "publicationYear": 2022,
    "isbn": "1234567890",
    "availabilityStatus": "Available"
}

### Modify book
PUT http://localhost:3000/books/[ID] HTTP/1.1
Content-Type: application/json

{
    "title": "Updated Book Title",
    "author": "Updated Author",
    "genre": "Non-fiction",
    "publicationYear": 2023,
    "isbn": "0987654321",
    "availabilityStatus": "Checked Out"
}

### Delete book
DELETE http://localhost:3000/books/[ID]





// Render
### Home page
GET https://cse341contactproject.onrender.com

### All contacts
GET https://cse341contactproject.onrender.com/contacts

### Single contact
GET https://cse341contactproject.onrender.com/contacts/[id]

### Create contact
POST  https://cse341contactproject.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jDoe@test.org",
    "favoriteColor": "Beige",
    "birthday": "January 1st 1999"
}
### Modify contact
PUT  https://cse341contactproject.onrender.com/contacts/[id]
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Jane",
    "email": "Mary@jane.com",
    "favoriteColor": "Maroon",
    "birthday": "February 28th 2002"
}
### Delete contact
DELETE https://cse341contactproject.onrender.com/contacts/[id]